### ISSUE TITLE
Chat Not Found!

### ISSUE THREAD

**Issue by mhmdrzkii** [St0rm1k/chatmoder_tgpy#2]
hi, i tried it and got this error

`INFO:aiogram:Bot: Tukang Mute [@tukangmuter_bot]
WARNING:aiogram:Updates were skipped successfully.
WARNING:aiogram:Goodbye!
Traceback (most recent call last):
  File "c:\Users\AdministratorBOT\Documents\TgChatModerator\main.py", line 223, in <module>
    executor.start_polling(dp, on_startup=send_adm, skip_updates=True)
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\executor.py", line 45, in start_polling
    executor.start_polling(
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\executor.py", line 320, in start_polling
    loop.run_until_complete(self._startup_polling())
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\executor.py", line 377, in _startup_polling
    await callback(self.dispatcher)
  File "c:\Users\AdministratorBOT\Documents\TgChatModerator\main.py", line 13, in send_adm
    await bot.send_message(chat_id=adminId, text='Bot started!')
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\bot.py", line 339, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "C:\Users\AdministratorBOT\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found`

how i can solved that?

**Comment by mr-st0rm** [comment]
check your admin_id in config, and start bot, bot can't send mesasge to you

**Comment by mhmdrzkii** [comment]
ok sir thats work

**Comment by mhmdrzkii** [comment]
bot just replied _muted for_ but not restricted of target
